# Number of days of inactivity before an issue becomes stale
daysUntilStale: 60
# Number of days of inactivity before a stale issue is closed
daysUntilClose: 7
# Issues with these labels will never be considered stale
exemptLabels:
  - "k: Feature"
  - "s: Accepted"
# Label to use when marking an issue as stale
staleLabel: "s: Stale"
# Comment to post when marking an issue as stale. Set to `false` to disable
markComment: >
  Este problema se ha marcado automáticamente como obsoleto porque no ha tenido
  Actividad reciente. Se cerrará si no se produce más actividad. Gracias
  por tus aportes.
# Comment to post when closing a stale issue. Set to `false` to disable
closeComment: false