name: Advocatus Build
on:
  push:
    branches:
      - beta
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [11]
      fail-fast: true
    steps:
      - uses: actions/checkout@v2
      - name: Install Java ${{ matrix.java }}
        uses: actions/setup-java@v2
        with:
          java-version: ${{ matrix.java }}
          distribution: 'adopt'
      - name: configure
        run: |
          git config --global user.email "no-reply@github.com"
          git config --global user.name "Github Actions"
          chmod +x advocatus
          chmod +x scripts/*.sh
      - name: Setup Maven
        uses: s4u/maven-settings-action@v2.3.0
        with:
          servers: |
            [{
              "id": "royalmind",
              "username": "${{ secrets.PACKAGES_USERNAME }}",
              "password": "${{ secrets.PACKAGES_PASSWORD }}"
            }]
          mirrors: |
            [{
              "id": "royalmind",
              "name":"rms",
              "mirrorOf":"royalmind",
              "url":"http://ns529965.ip-149-56-107.net:8081/repository/maven-public/"
            }]
      - name: patch for Java ${{ matrix.java }}
        run: ./advocatus p
      - name: build for Java ${{ matrix.java }}
        run: mvn -X clean javadoc:javadoc package "-Dbuild.number=${{ github.run_number }}"
      - name: deploy for Java ${{ matrix.java }}
        run: mvn deploy "-Dbuild.number=${{ github.run_number }}"
      # An artifact is generated in a compressed file according to each JDK build version.
      - name: Upload Artifact Advocatus Proxy for Java ${{ matrix.java }}
        uses: actions/upload-artifact@v2.2.4
        with:
          name: Java-JDK${{ matrix.java }} Advocatus J${{matrix.java}}
          path: Advocatus-Proxy/bootstrap/target/Advocatus.jar
      # cmd_alert
      - name: Upload Artifact Advocatus cmd-alert for Java ${{ matrix.java }}
        uses: actions/upload-artifact@v2.2.4
        with:
          name: Java-JDK${{ matrix.java }} modules J${{matrix.java}}
          path: Advocatus-Proxy/module/cmd-alert/target/cmd_alert.jar
      # cmd_find.jar
      - name: Upload Artifact Advocatus cmd_find for Java ${{ matrix.java }}
        uses: actions/upload-artifact@v2.2.4
        with:
          name: Java-JDK${{ matrix.java }} modules J${{matrix.java}}
          path: Advocatus-Proxy/module/cmd-find/target/cmd_find.jar
      # cmd_list.jar
      - name: Upload Artifact Advocatus cmd-list for Java ${{ matrix.java }}
        uses: actions/upload-artifact@v2.2.4
        with:
          name: Java-JDK${{ matrix.java }} modules J${{matrix.java}}
          path: Advocatus-Proxy/module/cmd-list/target/cmd_list.jar
      # cmd_send.jar
      - name: Upload Artifact Advocatus cmd-send for Java ${{ matrix.java }}
        uses: actions/upload-artifact@v2.2.4
        with:
          name: Java-JDK${{ matrix.java }} modules J${{matrix.java}}
          path: Advocatus-Proxy/module/cmd-send/target/cmd_send.jar
      # cmd_server.jar
      - name: Upload Artifact Advocatus cmd_server for Java ${{ matrix.java }}
        uses: actions/upload-artifact@v2.2.4
        with:
          name: Java-JDK${{ matrix.java }} modules J${{matrix.java}}
          path: Advocatus-Proxy/module/cmd-server/target/cmd_server.jar
      # reconnect_yaml.jar
      - name: Upload Artifact Advocatus reconnect_yaml for Java ${{ matrix.java }}
        uses: actions/upload-artifact@v2.2.4
        with:
          name: Java-JDK${{ matrix.java }} modules J${{matrix.java}}
          path: Advocatus-Proxy/module/reconnect-yaml/target/reconnect_yaml.jar
